### ISSUE TITLE
Log message order can be lost

### ISSUE THREAD

**Issue by lightoze** [tdomzal/junit-docker-rule#41]
Try out this example:
```java
    @Rule
    public DockerRule dbRule = DockerRule.builder()
            .imageName("postgres:9.6")
            .name("db-test")
            .restartPolicy(RestartPolicy.always())
            .expose("5432")
            .env("POSTGRES_USER", "testdb")
            .env("POSTGRES_PASSWORD", "testdb")
            .waitFor(WaitFor.logMessageSequence("PostgreSQL init process complete", "database system is ready to accept connections"))
            .waitFor(WaitFor.tcpPort(5432))
            .build();
```
First message arrives by stdout, second via stderr. They are shown in consistent order when viewing via `docker logs`, but the rule above often fails to match the condition.

**Comment by tdomzal** [comment]
Hi,
Looking at current implementation I can confirm this is possible because streams of stdout / stderr messages are processed independently.
This behavior can be definitely changed at the expense of losing distinction between stderr and stdout in messages logged by the library ("id-stdout> ..." and "id-stderr> ... " outputs) but let me look for some other solution.

**Comment by lightoze** [comment]
Thanks! Will give it a try after next release. Btw, snapshot builds are missing.

**Comment by tdomzal** [comment]
I just deployed 0.4-SNAPSHOT to oss sonatype repo.
Please report back if fix is working for you.
And thanks for reporting !

**Comment by lightoze** [comment]
Yeah, can confirm, the fix works correctly.
